# values must be base64 encoded
# encode: echo -n "your-value" | base64
# decode: echo "encoded-value" | base64 -d
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: default
type: Opaque
data:
  DB_USER: YWRtaW4=
  DB_PASSWORD: cGFzc3dvcmQxMjM=
